# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000-3001

# Command to start on workspace startup (optional)
tasks:
  - init: |
      psql < server/sql/bootstrap_db.sql
      psql --username=api  knikkerbaan < server/sql/create_tables.sql
      psql --username=api  knikkerbaan < server/sql/seed.sql
  - command: cd server/src && yarn config set script-shell /bin/bash && yarn install && node index.js 