DROP TABLE IF EXISTS algemeen;
DROP TABLE IF EXISTS buttonPresses;

CREATE TABLE algemeen (
  ID SERIAL PRIMARY KEY,
  naam VARCHAR(15) UNIQUE,
  waarde INTEGER
);

CREATE TABLE buttonPresses (
  ID SERIAL PRIMARY KEY,
  tijd TIMESTAMP WITH TIME ZONE NOT NULL
);